### ISSUE TITLE
TypeError: Cannot read property 'json' of undefined

### ISSUE THREAD

**Issue by zintarweb** [TwilioDevEd/authy2fa-node#8]
error in server after signing up a new account:

$ nodejs .
Express server started on *:3000
::ffff:10.0.0.123 - - [25/Jan/2017:22:53:29 +0000] "POST /session HTTP/1.1" 403 65 "http://192.168.1.40:3000/" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0"
::ffff:10.0.0.123 - - [25/Jan/2017:22:53:41 +0000] "POST /session HTTP/1.1" 403 65 "http://192.168.1.40:3000/" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0"
::ffff:10.0.0.123 - - [25/Jan/2017:22:54:31 +0000] "POST /user HTTP/1.1" 200 48 "http://192.168.1.40:3000/" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0"
::ffff:10.0.0.123 - - [25/Jan/2017:22:54:31 +0000] "GET /user HTTP/1.1" 200 74 "http://192.168.1.40:3000/" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0"
/var/appdata/authy2fa-node/models/User.js:68
                response.json(err);
                        ^

TypeError: Cannot read property 'json' of undefined
    at /var/appdata/authy2fa-node/models/User.js:68:25
    at Request.callback_check [as _callback] (/var/appdata/authy2fa-node/node_modules/authy/index.js:141:17)
    at Request.self.callback (/var/appdata/authy2fa-node/node_modules/request/request.js:236:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/appdata/authy2fa-node/node_modules/request/request.js:1142:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/appdata/authy2fa-node/node_modules/request/request.js:1096:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by dprothero** [comment]
This is likely due to not having set the `AUTHY_API_KEY` environment variable to a valid Authy API Key. It could be something else, however, so I've checked in a fix to the error handling code so it will give you the precise error code and message.
